// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc620.programmingchassisbasecode.subsystems;

import edu.wpi.first.wpilibj.Timer;
import java.util.TimerTask;

//import org.usfirst.frc620.programmingchassisbasecode.commands.joystickDrive;

import edu.wpi.first.wpilibj.SensorBase; 
import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.I2C.Port;
import edu.wpi.first.wpilibj.Timer; 
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class Lidar extends SensorBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	I2C m_i2c; 
	public Lidar() {  
    	m_i2c = new I2C(I2C.Port.kMXP,0x62);
    	initLidar();     	          	  
    }
    
    public void initLidar(){		
       // nothing to do
	}

	public int getDistance() {
 
		byte[] buffer;  	
		buffer = new byte[2];
	
		m_i2c.write(0x00, 0x04);
		Timer.delay(0.1);
		m_i2c.read(0x8f, 2, buffer);  	

  	
		return (int)Integer.toUnsignedLong(buffer[0] << 8) + Byte.toUnsignedInt(buffer[1]);
	}
	

	public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
	
}