// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc620.programmingchassisbasecode;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon drivetrainCANTalon1;
    public static CANTalon drivetrainCANTalon2;
    public static CANTalon drivetrainCANTalon3;
    public static CANTalon drivetrainCANTalon4;
    public static RobotDrive driveTrainRobotDrive41;
    public static DoubleSolenoid dsolenoid ;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
    	//ADD Solenoid
    	dsolenoid = new DoubleSolenoid(0,0,1);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainCANTalon1 = new CANTalon(1);
        LiveWindow.addActuator("Drivetrain", "CAN Talon 1", drivetrainCANTalon1);
        
        drivetrainCANTalon2 = new CANTalon(2);
        LiveWindow.addActuator("Drivetrain", "CAN Talon 2", drivetrainCANTalon2);
        
        drivetrainCANTalon3 = new CANTalon(3);
        LiveWindow.addActuator("Drivetrain", "CAN Talon 3", drivetrainCANTalon3);
        
        drivetrainCANTalon4 = new CANTalon(4);
        LiveWindow.addActuator("Drivetrain", "CAN Talon 4", drivetrainCANTalon4);
        
        driveTrainRobotDrive41 = new RobotDrive(
       		 drivetrainCANTalon1, 
       		 drivetrainCANTalon2,
       		 drivetrainCANTalon3, 
       		 drivetrainCANTalon4);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
