// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc620.Kevin;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Ultrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainLF;
    public static CANTalon driveTrainLB;
    public static CANTalon driveTrainRF;
    public static CANTalon driveTrainRB;
    public static RobotDrive robotDrive;
    public static DigitalInput bucketLimitUpper;
    public static DigitalInput bucketLimitLower;
    public static CANTalon bucketTalon;
    public static DoubleSolenoid lifterTopDS;
    public static DoubleSolenoid lifterBotDS;
    public static Ultrasonic lidar;
    public static PowerDistributionPanel powerDistroBoard;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLF = new CANTalon(1);
        LiveWindow.addActuator("Drive Train", "Left Front", driveTrainLF);
        
        driveTrainLB = new CANTalon(2);
        LiveWindow.addActuator("Drive Train", "Left Back", driveTrainLB);
        
        driveTrainRF = new CANTalon(3);
        LiveWindow.addActuator("Drive Train", "Right Front", driveTrainRF);
        
        driveTrainRB = new CANTalon(4);
        LiveWindow.addActuator("Drive Train", "Right Back", driveTrainRB);
        
        robotDrive = new RobotDrive(driveTrainLF, driveTrainLB,
              driveTrainRF, driveTrainRB);
        
        robotDrive.setSafetyEnabled(true);
        robotDrive.setExpiration(0.1);
        robotDrive.setSensitivity(0.5);
        robotDrive.setMaxOutput(1.0);

        bucketLimitUpper = new DigitalInput(0);
        LiveWindow.addSensor("Bucket", "Limit Upper", bucketLimitUpper);
        
        bucketLimitLower = new DigitalInput(1);
        LiveWindow.addSensor("Bucket", "Limit Lower", bucketLimitLower);
        
        bucketTalon = new CANTalon(5);
        LiveWindow.addActuator("Bucket", "Window Motor", bucketTalon);
        
        lifterTopDS = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Lifter", "Double Solenoid 1", lifterTopDS);
        
        lifterBotDS = new DoubleSolenoid(0, 2, 3);
        LiveWindow.addActuator("Lifter", "Double Solenoid 2", lifterBotDS);
        
        lidar = new Ultrasonic(2, 3);
        LiveWindow.addSensor("Lidar", "LidarSensor", lidar);
        
        powerDistroBoard = new PowerDistributionPanel(0);
        LiveWindow.addSensor("Power Bus", "powerBoard", powerDistroBoard);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
