// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package src.org.usfirst.frc620.Kevin.subsystems;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;
import src.org.usfirst.frc620.Kevin.RobotMap;

public class Lifter extends Subsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	private final DoubleSolenoid top = RobotMap.lifterTopDS;
	private final DoubleSolenoid bot = RobotMap.lifterBotDS;
	
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.
	
	public void extendTop() {
		top.set(DoubleSolenoid.Value.kForward);
	}
	
	public void extendBot() {
		bot.set(DoubleSolenoid.Value.kForward);
	}
	
	public void retractTop() {
		top.set(DoubleSolenoid.Value.kReverse);
	}
	
	public void retractBot() {
		bot.set(DoubleSolenoid.Value.kReverse);
	}
	
	public void stopTop() {
		top.set(DoubleSolenoid.Value.kOff);
	}

	public void stopBot() {
		bot.set(DoubleSolenoid.Value.kOff);
	}
	
	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}
}
